[project]
name = "gdpval-plots"
version = "0.1.0"
description = "Merge benchmark data and visualize model performance transformations."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "numpy",
    "pyyaml",
]

[tool.uv]
package = false
